@ChatApi_HostAddress = http://192.168.0.165:7190 

GET {{ChatApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ChatApi_HostAddress}}/chatbot/get

###

POST {{ChatApi_HostAddress}}/chatbot/post
Content-Type: application/json
Accept: application/json

{
  "message": "string"
}

###
