@ChatApi_HostAddress = http://localhost:5000 

GET {{ChatApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ChatApi_HostAddress}}/chatbot/get

###

POST {{ChatApi_HostAddress}}/chatbot/post
Content-Type: application/json
Accept: application/json

{
  "message": "string"
}

###
