version: '3'
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - network1
  api:
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - network1
  # proxy:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - network1
  #   links:
  #     - api
networks:
  network1: