version: '3'
services:
  redis:
    image: redis:latest
    networks:
      - network1

  api:
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    ports:
      - "5000"
    networks:
      - network1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - network1
    depends_on:
      - api

networks:
  network1: