version: '3'
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - network1

  api:
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    ports:
      - "5000"
    networks:
      - network1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network1
    depends_on:
      - api

networks:
  network1: